import React, { useEffect, useState } from 'react';
import { ScrollText, Printer, Loader2 } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

// IO — Warrant/Notice Draft Generator (auto-fills a legal template from real case fields)
export const WarrantGenerator: React.FC = () => {
  const { user } = useAuth();
  const [cases, setCases] = useState<any[]>([]);
  const [sel, setSel] = useState<any | null>(null);
  const [type, setType] = useState('CrPC 41A Notice of Appearance');
  const [loading, setLoading] = useState(true);

  useEffect(() => { (async () => { try { const r = await fetch('/api/catalyst/cases?limit=100'); const j = await r.json(); if (j.success) { setCases(j.cases); setSel(j.cases[0]); } } catch {} setLoading(false); })(); }, []);

  if (loading) return <div className="text-slate-500 text-sm flex items-center gap-2 p-6"><Loader2 className="w-4 h-4 animate-spin" /> Loading cases…</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between border-b border-navy-700 pb-4 no-print">
        <div>
          <h1 className="text-2xl font-bold tracking-wide text-slate-100 uppercase font-outfit flex items-center gap-2"><ScrollText className="w-7 h-7 text-amber-500" /> Warrant / Notice Generator</h1>
          <p className="text-sm text-slate-400">Auto-fills a legal notice template from real case fields, ready to export as PDF.</p>
        </div>
        <button onClick={() => window.print()} className="px-4 py-1.5 bg-amber-500 hover:bg-amber-600 text-navy-950 font-bold text-xs uppercase rounded-lg flex items-center gap-1.5"><Printer className="w-3.5 h-3.5" /> Export PDF</button>
      </div>

      <div className="flex flex-wrap items-center gap-3 no-print">
        <select value={sel?.id} onChange={(e) => setSel(cases.find((c) => c.id === e.target.value))} className="px-3 py-2 bg-navy-900 border border-navy-700 rounded text-slate-100 text-xs">
          {cases.map((c) => <option key={c.id} value={c.id}>{c.case_number} — {c.crime_type}</option>)}
        </select>
        <select value={type} onChange={(e) => setType(e.target.value)} className="px-3 py-2 bg-navy-900 border border-navy-700 rounded text-slate-100 text-xs">
          {['CrPC 41A Notice of Appearance', 'CrPC 91 Notice to Produce Documents', 'Search Warrant Request (Sec 93)'].map((t) => <option key={t}>{t}</option>)}
        </select>
      </div>

      {sel && (
        <div id="warrant" className="ops-card p-8 border border-navy-600 rounded-xl bg-navy-950 print:bg-white print:text-black font-serif space-y-4 text-slate-200 print:text-black">
          <div className="text-center border-b border-navy-700 print:border-gray-400 pb-3">
            <p className="font-bold text-lg">OFFICE OF THE INVESTIGATING OFFICER</p>
            <p className="text-sm">{sel.station} · {sel.district} District · Karnataka State Police</p>
          </div>
          <p className="text-center font-bold underline">{type}</p>
          <p className="text-sm leading-relaxed">Ref: FIR No. <b>{sel.case_number}</b>, registered on <b>{sel.date}</b> under investigation for the offence of <b>{sel.crime_type}</b>.</p>
          <p className="text-sm leading-relaxed">Whereas the above case is under investigation, and whereas your attendance / production is considered necessary for the purposes of this investigation, you are hereby directed to comply as required under the said provision of the Code of Criminal Procedure.</p>
          <p className="text-sm leading-relaxed">Brief facts on record: {sel.description}. Number of accused on record: {sel.accused_count}. Current status: {sel.status}.</p>
          <div className="pt-8 flex justify-between text-sm">
            <div><p>Place: {sel.district}</p><p>Date: {new Date().toLocaleDateString('en-GB')}</p></div>
            <div className="text-right"><p className="border-t border-slate-500 print:border-gray-500 pt-1 mt-8">{user?.name || 'Investigating Officer'}</p><p className="text-xs">{user?.badgeNumber || 'IO-402'} · {sel.station}</p></div>
          </div>
          <p className="text-[10px] text-slate-500 print:text-gray-500 font-mono">Auto-generated by SAHASRA from case record {sel.case_number} — verify all statutory particulars before service.</p>
        </div>
      )}
    </div>
  );
};
